version: "3.9"

services:
  server:
    build: ./server
    container_name: my-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  client:
    build: ./client
    container_name: my-client
    ports:
      - "80:80"

